<?php
/** Printable payslip — bare view; use the browser's Print → Save as PDF.
 * @var array $entry */
$allowances = [
    'Transport Allowance' => $entry['transport_allowance'],
    'Telephone Allowance' => $entry['telephone_allowance'],
    'Per Diem'            => $entry['per_diem'],
    'Overtime'            => $entry['overtime'],
    'Bonus'               => $entry['bonus'],
    'Commission'          => $entry['commission'],
];
$deductions = [
    'RSSB (employee)' => $entry['rssb_employee'],
    'PAYE'            => $entry['paye'],
    'Loan Repayment'  => $entry['loan_deduction'],
    'Salary Advance'  => $entry['advance_deduction'],
    'Other'           => $entry['other_deduction'],
];
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Payslip <?= e($entry['period_name']) ?> — <?= e($entry['employee_no']) ?></title>
<style>
  body { font-family: "Segoe UI", Arial, sans-serif; color: #1e293b; max-width: 760px; margin: 2rem auto; font-size: 14px; }
  .head { display: flex; justify-content: space-between; border-bottom: 3px solid #0b3d66; padding-bottom: 12px; }
  h1 { color: #0b3d66; font-size: 20px; margin: 0; }
  h2 { font-size: 15px; color: #0b3d66; margin: 22px 0 6px; }
  table { width: 100%; border-collapse: collapse; }
  td, th { padding: 6px 8px; border-bottom: 1px solid #e2e8f0; text-align: left; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  .total td { font-weight: 700; border-top: 2px solid #0b3d66; }
  .net { background: #ecfdf5; font-size: 16px; }
  .muted { color: #64748b; font-size: 12px; }
  .btn-print { background:#0b3d66; color:#fff; border:none; padding:8px 18px; border-radius:6px; cursor:pointer; }
  @media print { .no-print { display: none; } body { margin: 0; } }
</style>
</head>
<body>
<div class="no-print" style="text-align:right;margin-bottom:1rem">
  <button class="btn-print" onclick="window.print()">🖨 Print / Save as PDF</button>
</div>

<div class="head">
  <div>
    <h1>Premier Transport &amp; Tour Services Ltd</h1>
    <div class="muted">Kigali, Rwanda · hr@pts.rw</div>
  </div>
  <div style="text-align:right">
    <strong>PAYSLIP</strong><br>
    Period: <?= e($entry['period_name']) ?><br>
    <span class="muted"><?= e($entry['start_date']) ?> → <?= e($entry['end_date']) ?></span>
  </div>
</div>

<h2>Employee</h2>
<table>
  <tr><td>Name</td><td><?= e($entry['employee_name']) ?></td><td>Employee No.</td><td><?= e($entry['employee_no']) ?></td></tr>
  <tr><td>Department</td><td><?= e($entry['department'] ?? '—') ?></td><td>Position</td><td><?= e($entry['position'] ?? '—') ?></td></tr>
  <tr><td>RSSB No.</td><td><?= e($entry['rssb_number'] ?? '—') ?></td><td>TIN</td><td><?= e($entry['tin_number'] ?? '—') ?></td></tr>
  <tr><td>Bank</td><td><?= e($entry['bank_name'] ?? '—') ?></td><td>Account</td><td><?= e($entry['bank_account'] ?? '—') ?></td></tr>
</table>

<h2>Earnings</h2>
<table>
  <tr><td>Basic Salary</td><td class="num"><?= rwf($entry['basic_salary']) ?></td></tr>
  <?php foreach ($allowances as $labelText => $amount): if ((float) $amount > 0): ?>
    <tr><td><?= e($labelText) ?></td><td class="num"><?= rwf($amount) ?></td></tr>
  <?php endif; endforeach ?>
  <tr class="total"><td>Gross Salary</td><td class="num"><?= rwf($entry['gross_salary']) ?></td></tr>
</table>

<h2>Deductions</h2>
<table>
  <?php foreach ($deductions as $labelText => $amount): if ((float) $amount > 0): ?>
    <tr><td><?= e($labelText) ?></td><td class="num"><?= rwf($amount) ?></td></tr>
  <?php endif; endforeach ?>
  <tr class="total"><td>Total Deductions</td><td class="num">
    <?= rwf($entry['gross_salary'] - $entry['net_salary']) ?></td></tr>
</table>

<table style="margin-top:18px">
  <tr class="total net"><td>NET PAY</td><td class="num"><?= rwf($entry['net_salary']) ?></td></tr>
</table>

<p class="muted" style="margin-top:24px">
  Employer RSSB contribution (not deducted from salary): <?= rwf($entry['rssb_employer']) ?>.
  Generated by PTS HRMS on <?= date('d F Y') ?>. This is a computer-generated document.
</p>
</body>
</html>
